### ISSUE TITLE
Incorrect cache folder in readme.md

### ISSUE THREAD

**Issue by noc7c9** [shelfio/jest-mongodb#104]
The readme states that the binaries are downloaded to `~/.mongodb-binaries` but I don't think that's right.
According to [nodkz/mongodb-memory-server](https://github.com/nodkz/mongodb-memory-server#available-options) the default folder is `node_modules/.cache/mongodb-memory-server/mongodb-binaries`

A quick run seems to confirm that to be the right folder.

**Comment by noc7c9** [comment]
I wonder if you've set `MONGOMS_DOWNLOAD_DIR` in your `.bashrc` or something.

**Comment by vladgolubev** [comment]
Hey @noc7c9 

you're right! I believe that was the folder some long time ago. I'll update the readme asap

**Comment by vladgolubev** [comment]
Fixed by https://github.com/shelfio/jest-mongodb/commit/3485a367448d46769cb7a7a648cffe1d960090ed
