### ISSUE TITLE
Allow silencing the logs

### ISSUE THREAD

**Issue by noc7c9** [shelfio/jest-mongodb#105]
The logs creates a fair amount of noise to the test output. Using [debug](https://github.com/visionmedia/debug) might be a good way to keep the logs but exclude them for regular runs.

![Screen Shot 2019-05-01 at 1 16 28 PM](https://user-images.githubusercontent.com/3779513/57004609-9f0b3100-6c13-11e9-803e-c515b919214d.png)

**Comment by vladgolubev** [comment]
Thanks @noc7c9, I've just published `v1.0.1` with the fix https://github.com/shelfio/jest-mongodb/releases/tag/v1.0.1
