### ISSUE TITLE
Cannot find module '@shelf/jest-mongodb'

### ISSUE THREAD

**Issue by alex996** [shelfio/jest-mongodb#121]
I must be doing something stupid, but I can't seem to resolve `@shelf/jest-mongodb`. Here's a minimal repro:

```sh
$ npm i -D @shelf/jest-mongodb

$ echo "require('@shelf/jest-mongodb')" > test.js

$ node test.js

internal/modules/cjs/loader.js:626
    throw err;
    ^

Error: Cannot find module '@shelf/jest-mongodb'
```
At the same time,

```sh
$ cat node_modules/@shelf/jest-mongodb/package.json | grep name

    "name": "@shelf/jest-mongodb",
```

Any other package (incl. scoped) works. Originally ran into this with jest. I needs to use both `ts-jest` and `@shelf/jest-mongodb`, so I `require` both and then merge them with my own overwrites.

Env:
- `node -v`: `v12.3.1`
- `npm -v`: `6.9.0`

**Comment by KnupMan** [comment]
Can you please explain why do you need to resolve it?
If you wanna to use `@shelf/jest-mongodb` library properly, please look at the readme: https://github.com/shelfio/jest-mongodb#usage
You just need to add the library as Jest preset:
![image](https://user-images.githubusercontent.com/16997074/58787714-093c3a80-85f3-11e9-871b-052856a1b7bf.png)

**Comment by alex996** [comment]
@KnupMan As I mentioned briefly, I'm setting up Jest with TS and MongoDB, and `preset` only accepts a single string. The only workaround I found is to manually require both presets and merge them

```ts
const ts = require('ts-jest')
const mongo = require('@shelf/jest-mongodb')
const merge = require('merge')

module.exports = merge.recursive(ts, mongo, { /* overwrites */ })
```

However, that is beyond the point. I get the *exact same error* if I use `preset: '@shelf/jest-mongodb'` as you pointed out. I can provide a CodeSandbox repro if you'd like.

**Comment by chrisblossom** [comment]
You can require the exact file you need directly. For example: `require('@shelf/jest-mongodb/jest-preset')`.

I had the same issue because I need to have my own `globalSetup` file.

**Comment by vladgolubev** [comment]
@alex996 there is no `main` field in the `package.json` of the package, so Node doesn't know how to require this module

@chrisblossom is right, requiring a specific file will help

**Comment by sundowndev** [comment]
I'm having the same issue, I'm already using ts-jest preset, how should I do to use multiple presets ?

**Comment by Borduhh** [comment]
Had a similar issue and like @alex996 said, all Jest presets are just JS objects. Therefore you can merge them. He chose to use the merge NPM package, but you can also just use the object spread notation.

Here is my `jest.config.js` file:
```
const tsPreset = require('ts-jest/jest-preset');
const mongoPreset = require('@shelf/jest-mongodb/jest-preset');

const jestOverwrites = {
  testMatch: ['**/src/tests/**/?(*.)+(spec|test).ts?(x)'],
};

module.exports = { ...tsPreset, ...mongoPreset, ...jestOverwrites };
```

**Comment by LeoFC97** [comment]
I have a similar issue with @shelf/jest-mongodb/ and typeScript

Here is my jest.config.js file:
```
module.exports = merge.recursive(ts, mongo, {
  moduleNameMapper: {
    '^@/(.*)$': '<rootDir>/src/$1'
  },
  transform: {
    '^.+\\.(js|jsx)?$': 'ts-jest'
  },
  testMatch: [
    '<rootDir>/(src/**/*.test.ts)'
  ],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
})```
