### ISSUE TITLE
`MongoMemoryReplSet` support

### ISSUE THREAD

**Issue by j** [shelfio/jest-mongodb#152]
Is it possible to launch a replica set for transaction testing?

**Comment by vladgolubev** [comment]
Hey @j!

Frankly, that's not what I'm interested in developing personally right now, but I'll happily review & merge a pull request if somebody is willing to contribute this functionality!

**Comment by j** [comment]
I’ve since switched to mongo-runner for local development and CI and it seems faster than mongo memory server and is a more native feel. I’m getting detected open handles in jest with the replset so i got tired of dealing with it :/. I can add a PR though if they fix the issue.

**Comment by gabriellimoni** [comment]
Any updates on this issue?
