### ISSUE TITLE
Config dbName does not change global.__MONGO_DB_NAME__

### ISSUE THREAD

**Issue by jenlky** [shelfio/jest-mongodb#170]
Hi, I have been using this library for a while. I have noticed  `global.__MONGO_DB_NAME__` does not return the same dbname at the end of `global.__MONGO_URI__`. 

The dbName testing in `jest-mongodb-config` is reflected in `global.__MONGO_URI__` as `mongodb://127.0.0.1:52302/testing`. However, `global.__MONGO_DB_NAME__` shows `jest`.

I have forked and managed to fix it with one line. Going to make a PR. Please take a look.

**jest-mongodb-config**
```
module.exports = {
  mongodbMemoryServerOptions: {
    instance: {
      dbName: 'testing'
    },
    binary: {
      skipMD5: true
    },
    autoStart: false
  }
};
```

**mongo-aggregate.test.js**
```
  beforeAll(async () => {
    connection = await MongoClient.connect(global.__MONGO_URI__, {useNewUrlParser: true});
    
    console.log('global.__MONGO_URI__', global.__MONGO_URI__) 
    // returns mongodb://127.0.0.1:52302/testing
    
    console.log('global.__MONGO_DB_NAME__', global.__MONGO_DB_NAME__) 
    // returns jest

    db = await connection.db(global.__MONGO_DB_NAME__);
  });
```

![image](https://user-images.githubusercontent.com/30688276/65217446-a52c7c00-dae6-11e9-80a0-919051681c53.png)

**Comment by vladgolubev** [comment]
Fixed by https://github.com/shelfio/jest-mongodb/pull/171
