### ISSUE TITLE
TypeError: Cannot read property 'dbName' of undefined        

### ISSUE THREAD

**Issue by dannypk** [shelfio/jest-mongodb#172]
How it can be that updating a 'patch' version brings a "breaking change". 
Updating from 1.1.0 to 1.1.1 now i get the error in the title. Maybe add a default?

Also i would like to know the benefit that this change brings. What was the reason for it?

**Comment by vladgolubev** [comment]
Here is the reason for that fix: https://github.com/shelfio/jest-mongodb/issues/170
