### ISSUE TITLE
@shelf/jest-mongodb does not work with TypeScript

### ISSUE THREAD

**Issue by francesco-albanese** [shelfio/jest-mongodb#191]
Here the config I am using for jest in `jest.config.js`:

```js
module.exports = {
  transform: {
    '^.+\\.jsx?$': 'babel-jest',
    '^.+\\.ts?$': 'ts-jest'
  },
  rootDir: './lib',
  roots: ['<rootDir>'],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  preset: "@shelf/jest-mongodb"
};
```

Jest fails to run tests just saying "Determining test suites to run..."

Works if I replace ` preset: "@shelf/jest-mongodb"` with ` preset: "ts-jest"`

**Comment by asciidisco** [comment]
We use it with a Typescript setup, our `jest.config.js` looks like this:

```
const { defaults: tsjPreset } = require('ts-jest/presets')

module.exports = {
  preset: '@shelf/jest-mongodb',
  // ...some other non related config values...
  transform: tsjPreset.transform,
}
```

**Comment by francesco-albanese** [comment]
Actually I copy pasted the stuff about babel from another project, this is a node project strictly so there is no need to use babel-jest.

I replaced the configuration with this:

```js
const { defaults: tsjPreset } = require('ts-jest/presets')

module.exports = {
  transform: tsjPreset.transform,
  rootDir: './lib',
  roots: ['<rootDir>'],
  moduleFileExtensions: ['ts', 'js', 'json', 'node'],
  preset: "@shelf/jest-mongodb"
};
```

but still does not work. Keeps on saying "Determining test suites to run..."

**Comment by francesco-albanese** [comment]
Never mind, it was just the Docker image `node:alpine` which apparently is not compatible with mongodb-memory-server

**Comment by chanced** [comment]
@francesco-albanese You left this issue open. Sounds like you should be able to close it.

**Comment by gervasioartur** [comment]
I was having same error on Ubuntu 22, i just tried with a different OS like windows and it worked.

**Comment by Arcanorum** [comment]
> I was having same error on Ubuntu 22, i just tried with a different OS like windows and it worked.

Probably related: https://github.com/shelfio/jest-mongodb/issues/351
