### ISSUE TITLE
Support random database names

### ISSUE THREAD

**Issue by nitzano** [shelfio/jest-mongodb#192]
If I understood the the code correctly the configuration must include the `mongodbMemoryServerOptions.instance.dbName` key in  `jest-mongodb-config.js` file and fill it with a valid name.

 But if you check mongodb-memory-server options [here](https://github.com/nodkz/mongodb-memory-server#available-options-for-mongomemoryserver) you'll see that not supplying `dbName` will generate a random db name:

```dbName?: string, // by default generate random dbName```

Is this supported here as well? and if not can it be added so that tests can run in parallel with several databases at once?

**Comment by nataneb32** [comment]
I have a problem with async test, because it just create one database.  Sometimes with a lot of test, i receive random errors.

**Comment by randomhash** [comment]
now you can have random names ^_^
