### ISSUE TITLE
@shelf/jest-mongodb unpublished on NPM ?

### ISSUE THREAD

**Issue by Antonhansel** [shelfio/jest-mongodb#196]
Hello 😁

this repository seems to have been removed from NPM, https://www.npmjs.com/package/@shelf/jest-mongodb, is that a mistake ?

**Comment by vladgolubev** [comment]
Yes, that's a mistake! Thanks for bringing this up!

**Comment by vladgolubev** [comment]
Thanks @Antonhansel 

https://www.npmjs.com/package/@shelf/jest-mongodb is back to public again!

**Comment by Antonhansel** [comment]
Thank you for being so reactive 🙏
