### ISSUE TITLE
Any interest in a TypeScript port and/or definitions?

### ISSUE THREAD

**Issue by joeapearson** [shelfio/jest-mongodb#199]
I want to write a Jest environment that includes both MongoDB and some extra unique requirements.  I'd like to extend the good work already done in this repo rather than reinvent the wheel.

We're using TypeScript and naturally it complains that there are no type defs.  I'm ready to put in some work to create them.

I'd prefer _not_ to provide manual type definitions and publish them separately because they're a pain to write and maintain.  But I'd be happy to provide a complete port instead if that's interesting.  I thought I'd check if there is any interest or objection before doing so.

**Comment by randomhash** [comment]
@joeapearson hello, there are no objections for this kind of contribution. Moreover, it would nice to have ;)
