### ISSUE TITLE
Unrecognized pipeline stage name: '$unset'

### ISSUE THREAD

**Issue by suchy** [shelfio/jest-mongodb#200]
Hi,

I'm trying to test some of my code, where I'm using $unset stage when aggregating data and I'm getting this error:

```
MongoError: Unrecognized pipeline stage name: '$unset'
```

This is my jest-mogodb-config.js 

```
module.exports = {
  mongodbMemoryServerOptions: {
    instance: {
      dbName: 'jest'
    },
    binary: {
      skipMD5: true
    },
    autoStart: false
  }
};
```

What am I doing wrong?

Thanks!

**Comment by randomhash** [comment]
@suchy Hello. If it is still the case, could you please share the piece of code that you are trying to run?

**Comment by suchy** [comment]
@randomhash I went with different approach so can't tell if still an issue. Will close this issue ;-) Thanks for response!
