### ISSUE TITLE
Unknown linux distro elementary

### ISSUE THREAD

**Issue by erfanium** [shelfio/jest-mongodb#205]
I got `Unknown linux distro elementary` message.
Elementary is based on Ubuntu. It doesn't difference to you

**Comment by randomhash** [comment]
@erfanium hello, could you provide more details? In which stage it fails?

**Comment by erfanium** [comment]
@randomhash It doesn't fail, It's just a warning message, but everything works great, so you can ignore this message for `elementary` distro
