### ISSUE TITLE
Docs should point out parallel test issues

### ISSUE THREAD

**Issue by chrischen** [shelfio/jest-mongodb#206]
Running parallel tests has issues with this because one MongoDB instance is used for all tests.

If you have another test running concurrently that hits the the same collection it causes race conditions (if you clear the collection in between tests).

**Comment by sibelius** [comment]
check this for parallel tests https://itnext.io/parallel-testing-a-graphql-server-with-jest-44e206f3e7d2?gi=ae7fe1d294f6
