### ISSUE TITLE
globalConfig.json file location change

### ISSUE THREAD

**Issue by bbourn** [shelfio/jest-mongodb#214]
Whether on purpose or not, the location of the globalConfig.json changed to my projects root directory instead of @sheldfio in node_modules jest-mongodb root.

I have my own custom environment and have to deal with this file manually.  This broke my test environment until I put in a check for the new location.

**Comment by farhantahir** [comment]
Its happened to me as well, I added the file to .gitignore.

**Comment by afrittella** [comment]
Yep, it's here:
https://github.com/shelfio/jest-mongodb/commit/0b0161ce64d77573a8dd26e635c983ddf187edc4
