### ISSUE TITLE
How to use with ts-jest?

### ISSUE THREAD

**Issue by tbell511** [shelfio/jest-mongodb#239]
Has anybody gotten jest-mongodb to work with ts-jest?

They both require a preset, which I'm not sure how to get around 🤔 

preset for ts-jest is `ts-jest` VS `@shelf/jest-mongodb`

Thanks!

**Comment by tbell511** [comment]
Figured it out. For those that are also trying to solve I did this...

In `jest.config.js` I have,

```
const jest_mongodb = require("@shelf/jest-mongodb/jest-preset")

module.exports = {
	...jest_mongodb,
	preset: "ts-jest",
};
```

**Comment by the-vampiire** [comment]
thanks @tbell511 for anyone coming in 2022 i found i also needed to ignore .js files or it would run double the tests (ts and js)

> `jest.config.js`

```js
const jestMongoDbPreset = require("@shelf/jest-mongodb/jest-preset");

/** @type {import('ts-jest/dist/types').InitialOptionsTsJest} */
module.exports = {
  ...jestMongoDbPreset,
  preset: 'ts-jest',
  testPathIgnorePatterns: [".js"], // prevent duplicate tests of src/ (ts) and build/ (js)
};
```
