### ISSUE TITLE
Option to rename MONGO_URL

### ISSUE THREAD

**Issue by adamazad** [shelfio/jest-mongodb#241]
My setup requires that I load all constants from a single file - `src/constants/index.ts` and I have `.env.test` for testing. So, my preference is that I do use `MONGO_URI` instead of `MONGO_URL`. 

I have a proposal that we add another variable to `jest-mongodb-config.js`: 

```typescript
interface JestMongoDBConfig {
  mongodbMemoryServerOptions: MongoMemoryServerOptsT
  mongoURLEnvName?: string
}
```

`mongoURLEnvName` defaults back to `MONGO_URL`. I can submit a PR if the idea is appealing.

**Comment by vladgolubev** [comment]
Well, I don't object to that idea. I can see other people benefit from it. So the PR is welcome!

**Comment by rcg-dev** [comment]
A work around for want your own url is somewhere in your setup files to reassign the value

`process.env.MyDesiredURLName = proccess.env.MONGO_URL`

**Comment by jimrandomh** [comment]
Another reason for wanting it to be named something else: there are other systems around using the name `MONGO_URL` for their database, which creates a risk of accidentally connecting a unit tester to something else's database, which would be bad.

(This hasn't happened to anyone that I know of, but it would be pretty bad if it did, so worth taking steps to prevent.)
