### ISSUE TITLE
Operator $unset is not recognized

### ISSUE THREAD

**Issue by luanfonsecap** [shelfio/jest-mongodb#250]
Hi, 

I'm trying to test my function that uses the $ unset operator in your aggregation query, but it is not recognized, returning the error:

```
MongoError: Unrecognized pipeline stage name: '$unset'
```

My jest-mogodb-config.js: 

```js
module.exports = {
  mongodbMemoryServerOptions: {
    instance: {
      dbName: 'jest',
    },
    binary: {
      version: '4.0.2',
      skipMD5: true,
    },
    autoStart: false,
  },
};

```

Another issue has already been opened for this problem but has not yet been resolved:
https://github.com/shelfio/jest-mongodb/issues/200

This is a part of my query: 
```
        $unset: [
          'accountMemberId',
          'externalPaymentId',
          'person.phoneNumbers.accountMemberId',
          'accountMember',
        ],
      },
```

**Comment by vladgolubev** [comment]
Is this a part of a query or aggregation?

If this is a part of aggregation, please change Mongo version to 4.2+

It was not yet available in version 4.0
