### ISSUE TITLE
mongoose

### ISSUE THREAD

**Issue by sibelius** [shelfio/jest-mongodb#261]
It would be cool to add a new section explaining the usage with mongoose

**Comment by vladgolubev** [comment]
I've never used mongoose so I can only hope for others to fill this gap. Contributions are welcome

**Comment by leosuncin** [comment]
It almost the same as in the README, I used here https://github.com/leosuncin/fakeshop-api

```javascript
import mongoose from 'mongoose'

test('connect to db', async () => {
  await mongoose.connect(process.env.MONGO_URL)
  // The rest of the test
})
```

**Comment by OneCricketeer** [comment]
This is documented already in the memory server README

https://github.com/nodkz/mongodb-memory-server#simple-test-with-mongoclient-in-jest
