### ISSUE TITLE
(node:7357) [MDEP001] DeprecationWarning: "MongoMemoryReplSet.getConnectionString" is deprecated, use ".getUri"

### ISSUE THREAD

**Issue by sibelius** [shelfio/jest-mongodb#262]
(node:7357) [MDEP001] DeprecationWarning: "MongoMemoryReplSet.getConnectionString" is deprecated, use ".getUri"

We should fix this warning

**Comment by vladgolubev** [comment]
This looks like an issue in the dependency we use - https://github.com/nodkz/mongodb-memory-server

**Comment by jmbldwn** [comment]
The source of the warning is in setup.js
```
  const mongoConfig = {
    mongoUri: await mongod.getConnectionString(),
    mongoDBName: options.instance.dbName
  };
```

**Comment by arobld00** [comment]
@simonbrunel Hello! PR has been approved, could you merge it? Thank you very much :)

**Comment by KnupMan** [comment]
Thank you all for your contributions!
New version released at https://github.com/shelfio/jest-mongodb/releases/tag/v1.2.5
