### ISSUE TITLE
Support $search aggregate 

### ISSUE THREAD

**Issue by AlexanderKaran** [shelfio/jest-mongodb#271]
Hi 

Been using jest-mongodb for a while now, and it suits most test cases. Thanks for putting it together!

We recently added $search functionality to some of our aggregations and would like to test them, and the library sends back errors each time we try. 

Does the library currently support $search, and I am just using it wrong, or does it need adding?

If it needs adding, is it in the pipeline, or do you want me to have a crack at adding it in?

**Comment by vladgolubev** [comment]
Hi

What MongoDB version did you configure for `@shelf/jest-mongodb`? 

`$each` should work out of the box if you set a correct MongoDB version in the config

**Comment by AlexanderKaran** [comment]
Hi @vladgolubev 

Little confused I am referring to the search aggregation not $each: https://docs.mongodb.com/manual/reference/operator/aggregation/search/

**Comment by vladgolubev** [comment]
Hi @AlexanderKaran 

This library will support any operation that is supported by the mongodb version you set.

Documentation says, `$search` is supported since version 4.2. Could you confirm you're using version 4.2+ in your `jest-mongodb-config.js`?

```javascript
module.exports = {
  mongodbMemoryServerOptions: {
    binary: {
      version: '4.2.0', // Note the version here
      skipMD5: true
    },
    autoStart: false,
    instance: {}
  }
};

```

**Comment by AlexanderKaran** [comment]
All sorted thanks
