### ISSUE TITLE
Enable support to Mint LMDE versions

### ISSUE THREAD

**Issue by Gabriel-JM** [shelfio/jest-mongodb#281]
Currently the package only verifies the version of Ubuntu Mint distro, when using LDME the version is less then 17 and we get an unsupported version error...

**Comment by vladgolubev** [comment]
Do you mind sharing a stack trace of the error you're getting? I'm not sure I understand how this package can is related to Linux Mint...

**Comment by Gabriel-JM** [comment]
No I get the stack trace, the problem is that I get a error saying the version of Linux Mint that I'm using is not supported because is less than 17, and I'm using the LMDE version which that lastest version is 4, which means I always get this error even if the package actually works.

Just to test my theory, i went to the file `MongoBinaryDownloadUrl` which shows in stack trace and I set if version equals 4 set it to 20 and it actually works, no more errors.

Actually maybe this problem is not related directly to your package but some of the dependencies.

**Comment by Gabriel-JM** [comment]
Hello again, i found that the problem is in another lib, so thanks @vladgolubev for the attention!!!
