### ISSUE TITLE
bug: version 1.3.2 introduce breaking change

### ISSUE THREAD

**Issue by climba03003** [shelfio/jest-mongodb#288]
Reference Issue: https://github.com/nodkz/mongodb-memory-server/issues/491

`mongodb-memory-server@6.10.0` should not be used as it is a accidental release which introduce breaking change. We should target to `~6.9.0` or something like that to prevent breakage.

**Comment by vladgolubev** [comment]
Hey @climba03003 

Thanks for bringing this up.

I've just published version `1.3.4` that uses `mongodb-memory-server` version `6.9.6`.

Let me know does it work for you.

**Comment by climba03003** [comment]
Thanks. It works.
