### ISSUE TITLE
Test environment errors with Jest v28

### ISSUE THREAD

**Issue by letsgolesco** [shelfio/jest-mongodb#338]
When running tests after upgrading to Jest v28, the following error occurs:

```
  ● Test suite failed to run

    The error below may be caused by using the wrong test environment, see https://jestjs.io/docs/configuration#testenvironment-string.
    Consider using the "jsdom" test environment.
    
    ReferenceError: navigator is not defined
```

This is likely because of [a breaking change to custom environments](https://jestjs.io/docs/upgrading-to-jest28#custom-environment).

The constructor may be fine in its current state, but this is the suggestion from the Jest v28 upgrade guide:

```js
   constructor({globalConfig, projectConfig}, context) {
     super({globalConfig, projectConfig}, context);
```

However, the `jest-environment-node` import definitely needs to be updated to the following:

```js
 const {TestEnvironment} = require('jest-environment-node');
```

**Comment by nicolas-sicard-adeo** [comment]
Hi,

I also had a similar problem on my side when trying to run [stryker](https://github.com/stryker-mutator/stryker-js) with jest v28. 

jest-mongodb v2.2.2 was holding back the jest-environment-node to v27, i do not have the same problem with version 2.2.1

**Comment by vladgolubev** [comment]
Check out the new version 3.0.0 - https://github.com/shelfio/jest-mongodb/releases/tag/v3.0.0
