### ISSUE TITLE
Upgrade mongodb driver to 4.8

### ISSUE THREAD

**Issue by letsgolesco** [shelfio/jest-mongodb#369]
MongoDB 6.0 is generally available and requires NodeJS driver 4.8, according to the [compatibility chart](https://www.mongodb.com/docs/drivers/node/current/compatibility/). The version used by this package is currently locked to 4.7.0.

This upgrade would be greatly appreciated!

**Comment by letsgolesco** [comment]
This existing PR would resolve the issue https://github.com/shelfio/jest-mongodb/pull/363

**Comment by harazdovskiy** [comment]
Updated in the scope of [v4.1.0 release](https://github.com/shelfio/jest-mongodb/releases/tag/v4.1.0)
