### ISSUE TITLE
Upgrade mongodb-memory-server from major version 7 to 8

### ISSUE THREAD

**Issue by letsgolesco** [shelfio/jest-mongodb#370]
This package is still using an outdated version of `mongodb-memory-server`. In order to keep up with changes in MongoDB and its drivers, it would be best to keep up to date with the latest `mongodb-memory-server`.

PR https://github.com/shelfio/jest-mongodb/pull/310 has been open for a while and would achieve this upgrade.

**Comment by harazdovskiy** [comment]
Hi @letsgolesco, we are preparing ts support for `jest-mongodb`, and updating `mongodb-memory-server` is included in the scope!

**Comment by harazdovskiy** [comment]
Updated in scope of [v4.1.0 release](https://github.com/shelfio/jest-mongodb/releases/tag/v4.1.0)!

**Comment by letsgolesco** [comment]
Thanks @harazdovskiy !
