### ISSUE TITLE
Atlas search directives are not supported

### ISSUE THREAD

**Issue by AChusuei** [shelfio/jest-mongodb#398]
I am currently using Atlas search to do some queries and it would be good to be able to unit test those workflows, but when testing those workflows, I get this error: `Unrecognized pipeline stage name: '$search'`

I know the version of mongo that gets started up for jest is a local instance which will have no knowledge of Atlas, but is there a possibility to add support for this? More and more, folks or going to Atlas versus standing up their own instances of Mongo.

**Comment by vladgolubev** [comment]
Not technically possible. This is a proprietary Atlas feature not available in the open-source version of MongoDB
