### ISSUE TITLE
How can I provide the collection to the file under test.

### ISSUE THREAD

**Issue by Lyonsclay** [shelfio/jest-mongodb#4]
I used this repo to successfully setup mongodb in my test environment. It works great when I create and populate a collection within the test file, but when I import a method from another file that uses a collection it doesn't recognize it. Which isn't surprising.

Is there an example of how to set up a test mongodb with collections that are available to files that import them?

**Comment by RodolfoSilva** [comment]
@Lyonsclay check my project https://github.com/RodolfoSilva/graphql-typescript-server-boilerplate I'm using the solution proposed by @vladgolubev
