### ISSUE TITLE
TypeError: Class extends value undefined is not a constructor or null

### ISSUE THREAD

**Issue by crobinson42** [shelfio/jest-mongodb#406]
Jest v29 and this package v3 & v4 fail with all tests:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/5973579/205415841-39522aef-69b7-40b6-af25-903ad063189b.png">

```
TypeError: Class extends value undefined is not a constructor or null

      at Object.<anonymous> (node_modules/@shelf/jest-mongodb/lib/environment.js:15:70)
      at Object.newLoader (node_modules/pirates/lib/index.js:141:7)
      at ScriptTransformer.requireAndTranspileModule (node_modules/@jest/transform/build/ScriptTransformer.js:772:66)
```

Rolling back to v2 works as expected.

**Comment by GeoFro** [comment]
I'm getting the same
`    "jest": "^26.6.3",`

**Comment by stanyq4** [comment]
Bumping this up.

**Comment by stefdelec** [comment]
Same here

**Comment by mr-pinzhang** [comment]
getting same error though.

**Comment by mr-pinzhang** [comment]
The problem is that the export `TestEnvironment` from `jest-environment-node` only exists after version [`v28`](https://github.com/facebook/jest/commit/1b402ab76b8bd0f8c5c8512345e2fd7aca8d83ed). So either you'll need to upgrade your `jest-environment-node`, or downgrade `jest-mongodb` to `v2`.
