### ISSUE TITLE
useSharedDBForAllJestWorkers: false is not working and all jest workers are getting the same database URI

### ISSUE THREAD

**Issue by itai-gendler** [shelfio/jest-mongodb#430]
Hello.

First thanks for such a great library.

I am trying to run my jest tests suites in parallel but although following the docs each worker gets the same mongo uri in the `global.__MONGO_URI__`

i can easily see this because i am printing the uri and all suites are getting the same uri.

i am calling the connectToMongo from beforeAll in each suite.

i have tried to execute the tests in this repo but i am unable to get them to even run.

 
![code](https://github.com/shelfio/jest-mongodb/assets/16039521/69585d09-f33a-4eb1-97a9-22fdcea03824)
![code-mongo](https://github.com/shelfio/jest-mongodb/assets/16039521/9482ebe8-09a0-4c22-800f-93b358ac7341)
![code-3](https://github.com/shelfio/jest-mongodb/assets/16039521/366fe054-ba72-49ac-9a72-9388a42e6364)

**Comment by bene-we** [comment]
@itai-gendler have you tried moving the `useSharedDBForAllJestWorkers` prop one level up, like in the docs?

```
module.exports = {
  mongodbMemoryServerOptions: {
    binary: {
      skipMD5: true,
    },
    autoStart: false,
    instance: {},
  },

  useSharedDBForAllJestWorkers: false,
};
```

**Comment by itai-gendler** [comment]
Thanks @bene-we this worked!!!
