### ISSUE TITLE
Upgrade dependencies for mongodb@6 and higher

### ISSUE THREAD

**Issue by D0ud0v** [shelfio/jest-mongodb#437]
Hi guys,

Thank you for the good work you guys are providing. I am running across a small issue. At the moment I am working on a project that needs dependencies on testing mongodb using jest. We recently upgraded our altas cluster from mongo 5 to 7. And using that, we are currently using a node project to automate SearchIndexes creations. Which is only available in the mongodb@6.0.0 @ mongodb@6.1.0 packages :
Here is the build error log

```
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: mongodb@6.1.0
npm ERR! node_modules/mongodb
npm ERR!   mongodb@"^6.1.0" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer mongodb@"3.x.x || 4.x || 5.x" from @shelf/jest-mongodb@4.1.7
npm ERR! node_modules/@shelf/jest-mongodb
npm ERR!   dev @shelf/jest-mongodb@"^4.1.7" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Is there a plan on upgrading dependencies to handle mongodb client 6+ on node ?

Here's the functionality :
https://github.com/mongodb/node-mongodb-native/tree/v6.1.0/src/operations/search_indexes

I know the package came out really early, but I'm kinda stuck with it atm.

Thanks for the reply !
Denis.

**Comment by JussiLem** [comment]
Looking forward to this as well

**Comment by jrh-exacta** [comment]
yep, I could use this functionality as well +1

**Comment by devsakae** [comment]
Same here

**Comment by rick-shar** [comment]
Same
