### ISSUE TITLE
[question] closing mongo connection twice

### ISSUE THREAD

**Issue by jirikrepl** [shelfio/jest-mongodb#89]
Is it necessary to call the `close()` for the second time?
https://github.com/vladgolubev/jest-mongodb/blob/master/mongo-insert.test.js#L14

I see in mongo example the call `close()` only on `mongoClient` object
https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html#open

**Comment by jeffski13** [comment]
> Is it necessary to call the `close()` for the second time?
> https://github.com/vladgolubev/jest-mongodb/blob/master/mongo-insert.test.js#L14
> 
> I see in mongo example the call `close()` only on `mongoClient` object
> https://mongodb.github.io/node-mongodb-native/api-generated/mongoclient.html#open

I also noticed the change to closing through the client instead of the db object 
https://stackoverflow.com/questions/50580673/typeerror-db-close-is-not-a-function

**Comment by vladgolubev** [comment]
Thanks guys, I've just fixed this in https://github.com/shelfio/jest-mongodb/commit/55c96254b902c3a9b8983224f8b827a78bb6a7a0 and published in `v1.0.1` https://github.com/shelfio/jest-mongodb/releases/tag/v1.0.1
